services:
  postgres:
    image: postgres:16-alpine
    container_name: maria-postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: maria-postgres
      POSTGRES_USER: maria
      POSTGRES_PASSWORD: maria321

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U maria -d maria-postgres
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

    restart: unless-stopped

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"  

volumes:
  postgres_data:
